# Generated by Django 3.1.7 on 2021-05-15 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rfq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coke', models.IntegerField(default=50)),
                ('pepsi', models.IntegerField(default=50)),
                ('soda', models.IntegerField(default=50)),
                ('quality', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
