# Generated by Django 3.1.7 on 2021-05-15 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfq',
            name='machine_no',
            field=models.IntegerField(default=1),
        ),
    ]
