# Generated by Django 3.1.7 on 2021-05-15 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_rfq_machine_no'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rfq',
            new_name='Items',
        ),
    ]
