# Generated by Django 3.1.7 on 2021-05-15 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20210516_0219'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='namemach',
            field=models.TextField(blank=True, null=True),
        ),
    ]
